### PR TITLE
 Reformatted subpages

### PR DESCRIPTION
**Pull request by baynejen**
- Position the Gifs side by side with the text
- Reduce font size on mobile for subpages

### CODE REVIEW

**Comment by alexander-mead** [comment]
Ah, this new thing looks great. Thanks so much again. The only remaining problem (bug?) I get is that the final gif on the 'orbital resonance' section vanishes after it has played through once, whereas all the other gifs seem fine. Any ideas? Do you see the same behaviour?

Mead

**Comment by alexander-mead** [comment]
I also updated the text and stuff a bit.

**Comment by alexander-mead** [comment]
I see the gif vanish both when I view the .html on my computer using Chrome and when I look at the updated website here:

https://alexander-mead.github.io./orbital.html

Do you see the same thing?

**Comment by alexander-mead** [comment]
Also, are you able to change the colour of the title banners in orbits.html and gravity.html from blue to black?

**Comment by baynejen** [comment]
Ah, this is indeed very strange! I swapped out that gif for another one and it didn't do it, so I don't believe it's a problem with the code but an issue with that actual gif. Are you able to make it again, give it a new file name and try it? If it keeps doing it I'll have another look but can't see what the problem would be off the top of my head.

And changed the background colour. Was actually thinking about this yesterday so glad you brought it up.

**Comment by baynejen** [comment]
I tried duplicating the gif in other blocks too and it disappears as well, so I do think the issue is with the gif itself

**Comment by alexander-mead** [comment]
Urgh! I agree with you. I remade the gif and get the same problem...
bastard. I think the software I'm using to make the gif isn't entirely
devoid of bugs, so maybe it's not that surprising. Let me do some tinkering
and see if I can unfuck things.

**Pull request merged**
